app = "grapevineer-grpc-gateway"
primary_region = "nrt"

[build]
  image = "esh2n/grapevineer-grpc-gateway:latest"

[env]
  GRPC_GATEWAY_PORT="8080"
  SERVER_ADDRESS="grapevineer-grpc.fly.dev:443"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 8080
    handlers = ["http"]