// Code generated by ent, DO NOT EDIT.

package ent

import (
	"esh2n/grapevineer/ent/player"
	"esh2n/grapevineer/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	playerFields := schema.Player{}.Fields()
	_ = playerFields
	// playerDescPlayerID is the schema descriptor for player_id field.
	playerDescPlayerID := playerFields[1].Descriptor()
	// player.PlayerIDValidator is a validator for the "player_id" field. It is called by the builders before save.
	player.PlayerIDValidator = playerDescPlayerID.Validators[0].(func(string) error)
	// playerDescName is the schema descriptor for name field.
	playerDescName := playerFields[2].Descriptor()
	// player.NameValidator is a validator for the "name" field. It is called by the builders before save.
	player.NameValidator = playerDescName.Validators[0].(func(string) error)
	// playerDescRegion is the schema descriptor for region field.
	playerDescRegion := playerFields[3].Descriptor()
	// player.DefaultRegion holds the default value on creation for the region field.
	player.DefaultRegion = playerDescRegion.Default.(string)
	// player.RegionValidator is a validator for the "region" field. It is called by the builders before save.
	player.RegionValidator = playerDescRegion.Validators[0].(func(string) error)
}
