// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"esh2n/grapevineer/ent/predicate"
	"esh2n/grapevineer/ent/storeviewer"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StoreViewerQuery is the builder for querying StoreViewer entities.
type StoreViewerQuery struct {
	config
	ctx        *QueryContext
	order      []storeviewer.OrderOption
	inters     []Interceptor
	predicates []predicate.StoreViewer
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StoreViewerQuery builder.
func (svq *StoreViewerQuery) Where(ps ...predicate.StoreViewer) *StoreViewerQuery {
	svq.predicates = append(svq.predicates, ps...)
	return svq
}

// Limit the number of records to be returned by this query.
func (svq *StoreViewerQuery) Limit(limit int) *StoreViewerQuery {
	svq.ctx.Limit = &limit
	return svq
}

// Offset to start from.
func (svq *StoreViewerQuery) Offset(offset int) *StoreViewerQuery {
	svq.ctx.Offset = &offset
	return svq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (svq *StoreViewerQuery) Unique(unique bool) *StoreViewerQuery {
	svq.ctx.Unique = &unique
	return svq
}

// Order specifies how the records should be ordered.
func (svq *StoreViewerQuery) Order(o ...storeviewer.OrderOption) *StoreViewerQuery {
	svq.order = append(svq.order, o...)
	return svq
}

// First returns the first StoreViewer entity from the query.
// Returns a *NotFoundError when no StoreViewer was found.
func (svq *StoreViewerQuery) First(ctx context.Context) (*StoreViewer, error) {
	nodes, err := svq.Limit(1).All(setContextOp(ctx, svq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{storeviewer.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (svq *StoreViewerQuery) FirstX(ctx context.Context) *StoreViewer {
	node, err := svq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StoreViewer ID from the query.
// Returns a *NotFoundError when no StoreViewer ID was found.
func (svq *StoreViewerQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = svq.Limit(1).IDs(setContextOp(ctx, svq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{storeviewer.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (svq *StoreViewerQuery) FirstIDX(ctx context.Context) string {
	id, err := svq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StoreViewer entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StoreViewer entity is found.
// Returns a *NotFoundError when no StoreViewer entities are found.
func (svq *StoreViewerQuery) Only(ctx context.Context) (*StoreViewer, error) {
	nodes, err := svq.Limit(2).All(setContextOp(ctx, svq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{storeviewer.Label}
	default:
		return nil, &NotSingularError{storeviewer.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (svq *StoreViewerQuery) OnlyX(ctx context.Context) *StoreViewer {
	node, err := svq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StoreViewer ID in the query.
// Returns a *NotSingularError when more than one StoreViewer ID is found.
// Returns a *NotFoundError when no entities are found.
func (svq *StoreViewerQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = svq.Limit(2).IDs(setContextOp(ctx, svq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{storeviewer.Label}
	default:
		err = &NotSingularError{storeviewer.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (svq *StoreViewerQuery) OnlyIDX(ctx context.Context) string {
	id, err := svq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StoreViewers.
func (svq *StoreViewerQuery) All(ctx context.Context) ([]*StoreViewer, error) {
	ctx = setContextOp(ctx, svq.ctx, "All")
	if err := svq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*StoreViewer, *StoreViewerQuery]()
	return withInterceptors[[]*StoreViewer](ctx, svq, qr, svq.inters)
}

// AllX is like All, but panics if an error occurs.
func (svq *StoreViewerQuery) AllX(ctx context.Context) []*StoreViewer {
	nodes, err := svq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StoreViewer IDs.
func (svq *StoreViewerQuery) IDs(ctx context.Context) (ids []string, err error) {
	if svq.ctx.Unique == nil && svq.path != nil {
		svq.Unique(true)
	}
	ctx = setContextOp(ctx, svq.ctx, "IDs")
	if err = svq.Select(storeviewer.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (svq *StoreViewerQuery) IDsX(ctx context.Context) []string {
	ids, err := svq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (svq *StoreViewerQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, svq.ctx, "Count")
	if err := svq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, svq, querierCount[*StoreViewerQuery](), svq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (svq *StoreViewerQuery) CountX(ctx context.Context) int {
	count, err := svq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (svq *StoreViewerQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, svq.ctx, "Exist")
	switch _, err := svq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (svq *StoreViewerQuery) ExistX(ctx context.Context) bool {
	exist, err := svq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StoreViewerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (svq *StoreViewerQuery) Clone() *StoreViewerQuery {
	if svq == nil {
		return nil
	}
	return &StoreViewerQuery{
		config:     svq.config,
		ctx:        svq.ctx.Clone(),
		order:      append([]storeviewer.OrderOption{}, svq.order...),
		inters:     append([]Interceptor{}, svq.inters...),
		predicates: append([]predicate.StoreViewer{}, svq.predicates...),
		// clone intermediate query.
		sql:  svq.sql.Clone(),
		path: svq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PlayerID string `json:"player_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StoreViewer.Query().
//		GroupBy(storeviewer.FieldPlayerID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (svq *StoreViewerQuery) GroupBy(field string, fields ...string) *StoreViewerGroupBy {
	svq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StoreViewerGroupBy{build: svq}
	grbuild.flds = &svq.ctx.Fields
	grbuild.label = storeviewer.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PlayerID string `json:"player_id,omitempty"`
//	}
//
//	client.StoreViewer.Query().
//		Select(storeviewer.FieldPlayerID).
//		Scan(ctx, &v)
func (svq *StoreViewerQuery) Select(fields ...string) *StoreViewerSelect {
	svq.ctx.Fields = append(svq.ctx.Fields, fields...)
	sbuild := &StoreViewerSelect{StoreViewerQuery: svq}
	sbuild.label = storeviewer.Label
	sbuild.flds, sbuild.scan = &svq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StoreViewerSelect configured with the given aggregations.
func (svq *StoreViewerQuery) Aggregate(fns ...AggregateFunc) *StoreViewerSelect {
	return svq.Select().Aggregate(fns...)
}

func (svq *StoreViewerQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range svq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, svq); err != nil {
				return err
			}
		}
	}
	for _, f := range svq.ctx.Fields {
		if !storeviewer.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if svq.path != nil {
		prev, err := svq.path(ctx)
		if err != nil {
			return err
		}
		svq.sql = prev
	}
	return nil
}

func (svq *StoreViewerQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*StoreViewer, error) {
	var (
		nodes = []*StoreViewer{}
		_spec = svq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*StoreViewer).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &StoreViewer{config: svq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, svq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (svq *StoreViewerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := svq.querySpec()
	_spec.Node.Columns = svq.ctx.Fields
	if len(svq.ctx.Fields) > 0 {
		_spec.Unique = svq.ctx.Unique != nil && *svq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, svq.driver, _spec)
}

func (svq *StoreViewerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(storeviewer.Table, storeviewer.Columns, sqlgraph.NewFieldSpec(storeviewer.FieldID, field.TypeString))
	_spec.From = svq.sql
	if unique := svq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if svq.path != nil {
		_spec.Unique = true
	}
	if fields := svq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, storeviewer.FieldID)
		for i := range fields {
			if fields[i] != storeviewer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := svq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := svq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := svq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := svq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (svq *StoreViewerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(svq.driver.Dialect())
	t1 := builder.Table(storeviewer.Table)
	columns := svq.ctx.Fields
	if len(columns) == 0 {
		columns = storeviewer.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if svq.sql != nil {
		selector = svq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if svq.ctx.Unique != nil && *svq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range svq.predicates {
		p(selector)
	}
	for _, p := range svq.order {
		p(selector)
	}
	if offset := svq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := svq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StoreViewerGroupBy is the group-by builder for StoreViewer entities.
type StoreViewerGroupBy struct {
	selector
	build *StoreViewerQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (svgb *StoreViewerGroupBy) Aggregate(fns ...AggregateFunc) *StoreViewerGroupBy {
	svgb.fns = append(svgb.fns, fns...)
	return svgb
}

// Scan applies the selector query and scans the result into the given value.
func (svgb *StoreViewerGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, svgb.build.ctx, "GroupBy")
	if err := svgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StoreViewerQuery, *StoreViewerGroupBy](ctx, svgb.build, svgb, svgb.build.inters, v)
}

func (svgb *StoreViewerGroupBy) sqlScan(ctx context.Context, root *StoreViewerQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(svgb.fns))
	for _, fn := range svgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*svgb.flds)+len(svgb.fns))
		for _, f := range *svgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*svgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := svgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StoreViewerSelect is the builder for selecting fields of StoreViewer entities.
type StoreViewerSelect struct {
	*StoreViewerQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (svs *StoreViewerSelect) Aggregate(fns ...AggregateFunc) *StoreViewerSelect {
	svs.fns = append(svs.fns, fns...)
	return svs
}

// Scan applies the selector query and scans the result into the given value.
func (svs *StoreViewerSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, svs.ctx, "Select")
	if err := svs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StoreViewerQuery, *StoreViewerSelect](ctx, svs.StoreViewerQuery, svs, svs.inters, v)
}

func (svs *StoreViewerSelect) sqlScan(ctx context.Context, root *StoreViewerQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(svs.fns))
	for _, fn := range svs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*svs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := svs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
