// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"esh2n/grapevineer/ent/predicate"
	"esh2n/grapevineer/ent/storeviewer"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StoreViewerDelete is the builder for deleting a StoreViewer entity.
type StoreViewerDelete struct {
	config
	hooks    []Hook
	mutation *StoreViewerMutation
}

// Where appends a list predicates to the StoreViewerDelete builder.
func (svd *StoreViewerDelete) Where(ps ...predicate.StoreViewer) *StoreViewerDelete {
	svd.mutation.Where(ps...)
	return svd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (svd *StoreViewerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, svd.sqlExec, svd.mutation, svd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (svd *StoreViewerDelete) ExecX(ctx context.Context) int {
	n, err := svd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (svd *StoreViewerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(storeviewer.Table, sqlgraph.NewFieldSpec(storeviewer.FieldID, field.TypeString))
	if ps := svd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, svd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	svd.mutation.done = true
	return affected, err
}

// StoreViewerDeleteOne is the builder for deleting a single StoreViewer entity.
type StoreViewerDeleteOne struct {
	svd *StoreViewerDelete
}

// Where appends a list predicates to the StoreViewerDelete builder.
func (svdo *StoreViewerDeleteOne) Where(ps ...predicate.StoreViewer) *StoreViewerDeleteOne {
	svdo.svd.mutation.Where(ps...)
	return svdo
}

// Exec executes the deletion query.
func (svdo *StoreViewerDeleteOne) Exec(ctx context.Context) error {
	n, err := svdo.svd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{storeviewer.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (svdo *StoreViewerDeleteOne) ExecX(ctx context.Context) {
	if err := svdo.Exec(ctx); err != nil {
		panic(err)
	}
}
